### ISSUE TITLE
VirusTotal reports malicious code (false positive?)

### ISSUE THREAD

**Issue by ithinkandicode** [Basement-Renovator/basement-renovator#293] opened 2022-10-01 22:12 UTC
FYI, scanning the zip has 1 vendor reporting an issue on VirusTotal:
https://www.virustotal.com/gui/file/4e304b7cceeea0d91dd5c2f5cc78e3c391c9650848749ee1df910a9f3cf1858f

And scanning the EXE itself has 4 vendors reporting issues:
https://www.virustotal.com/gui/file/877bc07f5edac8384cd7c3118d5e0112aa7f37f010d8fa18e22a16642147b291

This is for version 3.1.47
https://github.com/Basement-Renovator/basement-renovator/releases/tag/3.1.47

**Comment by jerbmega** [comment] 2022-10-02 03:33
Duplicate of #261, see my comments there for further info.

**Closed** 2023-03-06 21:01 UTC
